# For most projects, this workflow file will not need changing; you simply need
# to commit it to your repository.
#

name: "Dependency Review"
on: [pull_request]
permissions:
  contents: read
jobs:
  dependency-review:
    runs-on: lever-self-hosted
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: critical
          fail-on-scopes: runtime, development
